### ISSUE TITLE
Horizontal and vertical scrollbars appear on home page

### ISSUE THREAD

**Issue by Garrett04** [KorryKatti/Mirage-web#14]
Horizontal and vertical scrollbars appear on the home page, which shouldn’t be the case.

![Screenshot 2024-10-07 154959](https://github.com/user-attachments/assets/03fbb487-de2d-4ea9-97c6-32ca434c46f3)

I've fixed it and would like to merge.

**Comment by KorryKatti** [comment]
assigning
