### ISSUE TITLE
A break

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage-web#18]
# Announcement

I know you all are in full force and working towards the UI for this web app. Unfortunately, I have to take a 10-day break as part of my college break, and my laptop won't be with me. So, I won't be able to merge PRs for some time, but I will be available for discussions on Discord and in the issues.

Sorry for the inconvenience, and I hope to see you soon—possibly by the 18th of October.

**Comment by Garrett04** [comment]
All good! Enjoy your break :grin:
