### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by tanish0912** [KorryKatti/Mirage-web#23]
<img width="330" alt="Screenshot 2024-10-08 at 3 09 31 PM" src="https://github.com/user-attachments/assets/4e8064c5-190d-4587-8abf-7b3f82dc5e5f">

I noticed that the site is not fully mobile responsive. I’d be happy to help fix that and enhance the overall user experience on mobile devices.

**Comment by tanish0912** [comment]
Please assign me this i am willing to work on this.

**Comment by KorryKatti** [comment]
Mirage will have a native android app , no need for mobile responsiveness. Thanks for your efforts tho
