### ISSUE TITLE
Better styling for home page

### ISSUE THREAD

**Issue by ParvamShah1** [KorryKatti/Mirage-web#29]
The current homepage UI is clean but lacks the visual appeal necessary to engage and attract users effectively. To enhance the user experience and create a more dynamic and visually captivating homepage, I suggest the following improvements:

Proposed Changes:

1. Center Align Text and Elements:

-->Update all text elements currently aligned to the left, centering them to create a balanced and cohesive layout.
-->Ensure that buttons and other interactive components are centered, with consistent padding and spacing to enhance usability.

2.Enhance Visual Appeal:

-->Incorporate visually appealing styles such as vibrant colors, gradients, and patterns to give the homepage a modern, engaging look.
-->Use design principles like visual hierarchy to emphasize key elements, making important content stand out.
3.Update Button Styling:

-->Add hover effects, rounded corners, and subtle shadows to make buttons more interactive and appealing.
-->Experiment with colors, gradients, and placement to align with the overall theme and create a more cohesive appearance.
4.Introduce Dynamic Components:

-->Integrate animations or transitions for elements like buttons, images, and icons to make the homepage feel more lively and interactive.
-->Consider adding subtle background animations or visual effects that align with the brand identity to enhance engagement.

Expected Outcome:

A visually appealing, dynamic, and user-friendly homepage with centered alignment and engaging elements that create a lasting impression on users.

**Comment by KorryKatti** [comment]
Not accepting any more PRs for index.html wrt issue #28

But please do show a preview and I might make an exception
