### ISSUE TITLE
Starting off

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage-web#3]
### Issue: UI Development for Mirage Chat App

Hello, Hacktoberfest participants!

As part of our Hacktoberfest project, we are looking for talented developers to help create a user interface for our chat app, Mirage. 

### What We Need
We need a user-friendly and visually appealing UI that interacts seamlessly with our backend server. The UI should allow users to create rooms, join existing rooms, send and receive messages, and manage their user experience effectively.

### Resources
You can check the list of endpoints that Mirage's server code utilizes for communication. This will provide you with all the necessary information on how to integrate the frontend with the backend:

- [Mirage Server Endpoints](https://github.com/KorryKatti/Mirage-web/blob/main/endpoints.md)

### How to Get Started
1. **Fork the repository** and clone it to your local machine.
2. Review the existing endpoints to understand the data flow and functionalities.
3. Start designing the UI based on the requirements of a chat application.
4. Submit your pull requests to contribute your work!

### Additional Notes
- Feel free to reach out if you have any questions or need clarification on the project.
- We encourage creativity in design and functionality, so bring your ideas to the table!

Looking forward to your contributions!

wrt #1

**Comment by KorryKatti** [comment]
## Launching Testnet Server for Mirage

We are excited to announce that in approximately 24 hours, we will launch the testnet server for Mirage! This will allow contributors to work with the endpoints without needing to install all the requirements and Python dependencies.

### What You Can Do
- **Experiment with Endpoints**: You can interact with the Mirage server endpoints and test the functionality without setting up a local environment.
- **Develop UI**: If you’re interested in creating a user interface for the chat application, this is a great opportunity!

Stay tuned for updates, and feel free to reach out if you have any questions!

**Comment by mahenoorsalat** [comment]
@KorryKatti 

I have a strong foundation in front-end technologies, and as a UI/UX designer, I am passionate about creating user-friendly and visually appealing interfaces. I would love the opportunity to contribute to the Mirage Chat App project. If possible, please assign me a task, as I am eager to get started and collaborate with the team!

**Comment by KorryKatti** [comment]
> @KorryKatti
> 
> I have a strong foundation in front-end technologies, and as a UI/UX designer, I am passionate about creating user-friendly and visually appealing interfaces. I would love the opportunity to contribute to the Mirage Chat App project. If possible, please assign me a task, as I am eager to get started and collaborate with the team!

assigned, will be waiting for your PR

**Comment by KorryKatti** [comment]
### NOTE :  ONLY LOOKING FOR DESIGING OF THE APP RIGHT NOW , CONNECTING THE BACKEND WILL BE DONE AFTER 10-12 DAYS

**Comment by KaranSingh36752** [comment]
@mahenoorsalat 
As you seem to have the ui foundation i am willing to work such that we handle it
@KorryKatti you can assign me also

**Comment by Vipul-Ydv** [comment]
HEY @KorryKatti i've made one page for the same can u assign me so that i can pull the page

**Comment by KorryKatti** [comment]
assigning now
