### ISSUE TITLE
Chat app ui and favicon

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage-web#30]
### Chat UI Design Challenge

Thank you all for your contributions to the `index.html` file! Your efforts are greatly appreciated, but to help the project move forward more effectively, we’re introducing a structured design challenge.

#### Challenge Overview:
We’re looking for contributors to develop the UI for the following pages:
1. **User Authentication Page**
2. **Chat Application Page**

Attached is a workflow image that should guide your design process.

#### Participation Guidelines:
- **First Come, First Serve:** I will assign tasks based on the order of comments, but I will generally wait 24 hours for other users to submit their code. This way, we can have a fair comparison and accept the PR with the best functionality.
- **Testing:** Please ensure you test your code before making a PR to guarantee a smooth review process.
- **Changes to `index.html`:** No more changes will be accepted for `index.html` unless they are significant improvements that solve an issue or enhance functionality, rather than just color and theme changes. Please refer to issues #28 and #18 for context.

#### Communication:
Feel free to DM me on my social media handles (mentioned on the Mirage-Web website) or contact me on Discord if you have any questions or need clarification.

#### How to Participate:
- Please comment below to express your interest, and I will assign you to the task.
- Once assigned, feel free to share your design ideas and any questions you may have in the comments.

Let’s collaborate to create an amazing user interface!

![image](https://github.com/user-attachments/assets/fd15fc74-6a47-4321-ac9e-02e98d8097d0)

**Comment by theDevSoham** [comment]
Good day @KorryKatti . Can I work on this issue? I'm thinking of making a separate page for authentication (signin.html) routed to /signin and perform the tasks there. Also I don't have any experience with generating designs, so I guess we can use community designs from Figma or Dribble right?

For example: https://www.figma.com/design/BviC65em6TlMIHjWtzmys9/Direct-messaging-app-(Community)?node-id=0-1&node-type=canvas&t=6WGCrQSIWWnT76Pq-0

**Comment by mahenoorsalat** [comment]
@KorryKatti I will work on this issue.. assign me please 

Thank you :)

**Comment by KorryKatti** [comment]
> Good day @KorryKatti . Can I work on this issue? I'm thinking of making a separate page for authentication (signin.html) routed to /signin and perform the tasks there. Also I don't have any experience with generating designs, so I guess we can use community designs from Figma or Dribble right?
> 
> For example: https://www.figma.com/design/BviC65em6TlMIHjWtzmys9/Direct-messaging-app-(Community)?node-id=0-1&node-type=canvas&t=6WGCrQSIWWnT76Pq-0

Instead of getting from figma , you could work only on the authentication page. How does that sound

**Comment by KorryKatti** [comment]
> @KorryKatti I will work on this issue.. assign me please
> 
> Thank you :)

assigning

**Comment by theDevSoham** [comment]
@KorryKatti I can do that

**Comment by KorryKatti** [comment]
> @KorryKatti I can do that

alright will look forward to the login/authentication page you are working on

**Comment by KaranSingh36752** [comment]
@KorryKatti, I am working on the chat UI and other utilities. You can assign tasks to me...
