### ISSUE TITLE
 Enhance Footer with Social Media Icons for GitHub and Twitter

### ISSUE THREAD

**Issue by Vimal290704** [KorryKatti/Mirage-web#34]
To improve the user interface and overall user experience of the Mirage web application, I propose replacing the current plain text links for GitHub and Twitter at the bottom of the home page with icon buttons. This change will not only enhance the aesthetics of the page but also provide a more intuitive and recognizable way for users to access the project's social media profile.

**Comment by Vimal290704** [comment]
@KorryKatti Hey, i can fix this issue, please assign this issue to me.

**Comment by KorryKatti** [comment]
> @KorryKatti Hey, i can fix this issue, please assign this issue to me.

later , please refer #28
