### ISSUE TITLE
Change footer

### ISSUE THREAD

**Issue by taneeshaa15** [KorryKatti/Mirage-web#36]
[x.com/dunkelkron](https://x.com/dunkelkron) | [github.com/korrykatti](https://github.com/korrykatti) | [korrykatti.github.io](https://korrykatti.github.io/)

Mirage is open source under the [MIT license](https://github.com/korrykatti/mirage/blob/main/LICENSE).

This should be little more down in the footer section.

**Comment by taneeshaa15** [comment]
@KorryKatti Please assign me this issue under hacktoberfest.

**Comment by KorryKatti** [comment]
#28
