### ISSUE TITLE
Enhance Interface Interaction with Hover Color Change

### ISSUE THREAD

**Issue by PragyaTripathi990** [KorryKatti/Mirage-web#38]
Description:

To improve the user interface and provide clearer feedback, we propose adding a color change effect to the interface elements on hover. This enhancement will help users identify which element they are interacting with, making the interface more intuitive and visually appealing.

Implementation Details:
Current State: Elements remain static without any visual feedback when hovered over.
Proposed Change: On mouse hover, the background color of the element should change to a lighter or more vibrant color. This can be implemented using CSS, utilizing the :hover pseudo-class.
Color Suggestions: Consider using a subtle shade that contrasts with the current element color, ensuring it remains accessible and visually pleasing.
<img width="1437" alt="Screenshot 2024-10-13 at 7 27 37 AM" src="https://github.com/user-attachments/assets/40107698-ca83-44a1-9930-f958b0dbc471">

**Comment by KorryKatti** [comment]
could you possibly show a preview ? Thanks for the issue

**Comment by Vardhan-Harsh07** [comment]
@PragyaTripathi990 i can resolve that issue assign it to me
