### ISSUE TITLE
Improve Webpage Responsiveness

### ISSUE THREAD

**Issue by PragyaTripathi990** [KorryKatti/Mirage-web#39]
To enhance the user experience across various devices, we need to improve the responsiveness of our webpage. Currently, the layout and content do not adjust effectively on different screen sizes, which can lead to usability issues and a suboptimal viewing experience for users on mobile, tablet, and desktop devices.

**Comment by KorryKatti** [comment]
please show a preview image

**Comment by KorryKatti** [comment]
also mirage-web isn't expected to work on mobile devices

**Comment by Anurag-singh-thakur** [comment]
@KorryKatti hey can i work on that please ...i have one of my application with the complete responsiveness ..attaching the link just for your faith . if you find that i can we a good choice for your application please assign this issue to me . url(https://voting-app-frontend-67ba.onrender.com/)

**Comment by KorryKatti** [comment]
> @KorryKatti hey can i work on that please ...i have one of my application with the complete responsiveness ..attaching the link just for your faith . if you find that i can we a good choice for your application please assign this issue to me . url(https://voting-app-frontend-67ba.onrender.com/)

oh it has already been fixed , i forgot to close the issue

sorry for the waste of your time
