### ISSUE TITLE
Enhance Error Handling

### ISSUE THREAD

**Issue by vidhvath28** [KorryKatti/Mirage-web#4]
Issue: The current documentation doesn't explicitly mention robust error handling for events like create_room, send_message, etc. For instance, users may try to create a room with a duplicate name, or join a room that doesn't exist, but there might not be proper feedback or error responses in the server.

**Comment by KorryKatti** [comment]
i believe there is a proper json response for all that , but i am willing to talk on it

**Comment by vidhvath28** [comment]
Ya sure, This project sounds interesting for me I would like to even contribute to this project.

**Comment by KorryKatti** [comment]
> Ya sure, This project sounds interesting for me I would like to even contribute to this project.

would love to have as many people on it :D
