### ISSUE TITLE
[Feature] : Implement Dark/Light Toggle Theme to the Website.

### ISSUE THREAD

**Issue by rajgharat07** [KorryKatti/Mirage-web#41]
## Description :
Add a toggle switch to allow users to switch between dark and light themes across the website. The toggle should be easily accessible and instantly apply the selected theme across all pages, providing a consistent experience. The theme selection should also be remembered between sessions, ensuring the user's preference is retained.

## Requirements :

- Toggle button for dark/light mode should be present in the navigation bar or a prominent, user-friendly location.
- On toggle, all elements (text, background, buttons, etc.) should seamlessly transition between light and dark themes.
- Implement smooth transitions between themes for better user experience.
- Ensure compatibility with all website components (e.g., Navbar, Footer, etc.).

**Comment by KorryKatti** [comment]
not needed , the site color right now is good to not require any inversion
