### ISSUE TITLE
making more friendly this websiet for end users by adding more UI/IX designs and animations

### ISSUE THREAD

**Issue by rahul-chakradhari** [KorryKatti/Mirage-web#42]

**Comment by KaranSingh36752** [comment]
@rahul-chakradhari we are not looking to increase the load on the landing page by adding the animations as we need to redirect to the chat UI from Get Started button.
but if you can help in UI/IX design sure you can propose some ideas.

**Comment by rahul-chakradhari** [comment]
ok sir @KaranSingh36752 please assign labels

**Comment by KorryKatti** [comment]
> ok sir @KaranSingh36752 please assign labels

checkout #30 for the ui enhancements on chat app ui
