### ISSUE TITLE
Add micro elements to the cards

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [KorryKatti/Mirage-web#53]
There is no micro elements to the cards so i will add some interactive elements to it while hovering so please do assign it

**Comment by KorryKatti** [comment]
> There is no micro elements to the cards so i will add some interactive elements to it while hovering so please do assign it

show a preview of what you are trying to achieve

**Comment by SHANMUGAPRIYA-1** [comment]
The cards present are so simple so i will add some micro elements like
hovering changing colors to make it neat amd creative
